### ISSUE TITLE
go wrong

### ISSUE THREAD

**Issue by friend-ma** [nowshad-sust/enron-sender-detection#1]
creating directory
Traceback (most recent call last):
  File "C:/Users/Master/Desktop/enron-sender-detection-master/copy_sent_mails.py", line 80, in <module>
    save_to_folder(mailbox_owner, subFolder, file, contents)
  File "C:/Users/Master/Desktop/enron-sender-detection-master/copy_sent_mails.py", line 37, in save_to_folder
    os.mkdir(OUTPUT_DIR + "/" + mailboxOwner)
WindowsError: [Error 3] : 'C:\\Users\\Master\\Desktop\\enron-sender-detection-master\\remail/allen-p'

Process finished with exit code 1

I tried your code with python3 and python2, but it is always an error. Why is that?

**Comment by nowshad-sust** [comment]
It's just an OS issue I guess, see the line 
`WindowsError: [Error 3] : 'C:\Users\Master\Desktop\enron-sender-detection-master\remail/allen-p'`
Here, the error shows the filepath is invalid for windows because of forward and backward slash issue

edit the code on line 33 and 37 
you need to change the `/` into `\`

**Comment by friend-ma** [comment]
I changed them ,but it still do't work....
in py2:
D:\python2\python.exe C:/Users/Master/Desktop/enron-sender-detection-master/copy_sent_mails.py
  File "C:/Users/Master/Desktop/enron-sender-detection-master/copy_sent_mails.py", line 33
    writepath = OUTPUT_DIR + "\" + mailboxOwner + "\" + filename
                                                               ^
SyntaxError: unexpected character after line continuation character

Process finished with exit code 1

in py3:
D:\python-3.6.2\python.exe C:/Users/Master/Desktop/enron-sender-detection-master/copy_sent_mails.py
  File "C:/Users/Master/Desktop/enron-sender-detection-master/copy_sent_mails.py", line 33
    writepath = OUTPUT_DIR + "\" + mailboxOwner + "\" + filename
                                                               ^
SyntaxError: unexpected character after line continuation character

Process finished with exit code 1

**Comment by friend-ma** [comment]
in py3:
`D:\python-3.6.2\python.exe C:/Users/Master/Desktop/enron-sender-detection-master/copy_sent_mails.py
  File "C:/Users/Master/Desktop/enron-sender-detection-master/copy_sent_mails.py", line 33
    writepath = OUTPUT_DIR + "\" + mailboxOwner + "\" + filename
                                                               ^
SyntaxError: unexpected character after line continuation character

Process finished with exit code 1
`

**Comment by friend-ma** [comment]
edit the code on line 33 go wrong :missing closing quote["]

**Comment by friend-ma** [comment]
I solved it .You did not set up a remail folder at the beginning

MAIL_DIR_PATH = os.path.abspath('maildir')
PREFIX_TRIM_AMOUNT = len(MAIL_DIR_PATH) + 1
MAX_USER_RUN_LIMIT = 500
MAX_USER_EMAILS_PER_FOLDER_FILE_LIMIT = 2000
os.mkdir("remail")
OUTPUT_DIR = os.path.abspath("remail")

**Comment by nowshad-sust** [comment]
nice! I did forget to include that in the readme.

**Comment by friend-ma** [comment]
thank you very much.

**Comment by friend-ma** [comment]
Do you have a reference for this project? I want to figure it out.

**Comment by friend-ma** [comment]
I don't understand zhe remail subfolder  named laike  allen-p,arnold-j,badeer-r
?

**Comment by nowshad-sust** [comment]
@friend-ma these are names of the owners of mailboxes. These also work as tags of data for training and testing later.

**Comment by friend-ma** [comment]
Naive Bayes classifier ~ 0.40( I tried)
why Naive Bayes is so low???

**Comment by friend-ma** [comment]
The third program has been running, no results ... Why?

**Comment by nowshad-sust** [comment]
@friend-ma it takes time and a good amount of cpu, memory

**Comment by friend-ma** [comment]
in  Naive Bayes   u can set alpha =0.0001,the current rate is ~0.70

`text_clf = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf', MultinomialNB(alpha=0.0001)),
])`

**Comment by nowshad-sust** [comment]
:+1: 
that's a good job
thank you
